"""Single source of truth for the MESFlow deployment guide.

Rendered two ways from the SAME data below (per bootstrap/AGENTS.md's "do
not maintain two unrelated copies" spirit, applied to docs):

1. The Bootstrap web page `/guide/deployment` (templates/guide_deployment.html
   loops over GUIDE below).
2. `bootstrap/docs/MESFLOW_SERVER_DEPLOYMENT_GUIDE.md`, generated by
   `bootstrap/scripts/generate_guide_doc.py` calling `render_markdown()`
   in this file. Re-run that script after editing this file; do not hand-edit
   the .md file directly or it will drift from the web page.

Every command/behavior described here was read from the actual current
implementation (bootstrap/app.py, bootstrap/install.sh, deploy-agent/agent.py,
deploy-agent/installer/install.sh, deploy-agent/docker/compose*.yml,
deploy-agent/package_installer.sh) on 2026-08-18 -- see
reports/BOOTSTRAP_DEPLOYMENT_GUIDE.md for the audit trail. If code and this
file ever disagree, the code is right; fix this file to match it.
"""
from __future__ import annotations

import html as _html

GUIDE_VERSION = "1.0.0"

# --------------------------------------------------------------------------
# Small helpers used while building the data below
# --------------------------------------------------------------------------
DEV = "dev"
SERVER = "server"
BROWSER = "browser"
MESFLOW_SERVER = "mesflow_server"  # same host as SERVER in practice, but the MESFlow
# password-recovery card labels it explicitly (task requirement: "Do not mix laptop and
# server commands" -- make unmistakable that these run on the server hosting MESFlow,
# not the laptop and not necessarily the same shell session as a Bootstrap/Agent step).
MACHINE_LABELS = {
    DEV: "CHẠY TRÊN MÁY DEV",
    SERVER: "CHẠY TRÊN SERVER",
    MESFLOW_SERVER: "CHẠY TRÊN SERVER MESFLOW",
    BROWSER: "TRÌNH DUYỆT (TRÊN LAPTOP)",
}


def c(machine: str, code: str, note: str | None = None) -> dict:
    """One copyable command block, labeled with the machine it runs on."""
    return {"machine": machine, "machine_label": MACHINE_LABELS[machine], "code": code.strip("\n"), "note": note}


def block(heading: str, commands: list[dict] | None = None, text: str | None = None, note: str | None = None) -> dict:
    return {"heading": heading, "commands": commands or [], "text": text, "note": note}


def step(step_id: str, num: str, title: str, purpose: str, where: str,
          blocks: list[dict], expected: str, on_error: str, next_: str) -> dict:
    return {
        "id": step_id, "num": num, "title": title, "purpose": purpose, "where": where,
        "blocks": blocks, "expected": expected, "on_error": on_error, "next": next_,
    }


# --------------------------------------------------------------------------
# 1. System architecture
# --------------------------------------------------------------------------
ARCHITECTURE_DIAGRAM = r"""
MÁY DEV (workspace nguồn)
  │
  ├─ MESFlow (mesflow/)            source code
  ├─ QA Center (qa-center/)        source code
  ├─ Deploy Agent DEV (:8090)      SERVER_ROLE=DEV, build bật
  │
  │  build một lần → package/image bất biến (version + SHA256 + digest cố định)
  │
  ▼
PRODUCTION TEST (server test riêng, không phải thật)
  ├─ Bootstrap        :8098   (cài & cứu hộ Deploy Agent)
  ├─ Deploy Agent      :8090   SERVER_ROLE=PRODUCTION_TEST, build TẮT
  ├─ PostgreSQL                (container "postgres", do MESFlow compose quản lý)
  ├─ MESFlow (mesflow-app)  :8080
  └─ QA Center         :8095

  │  chỉ đi tiếp sau khi có TEST_PASS + con người bấm duyệt
  ▼
PRODUCTION (server thật, mesflow.net)
  ├─ Bootstrap        :8098
  ├─ Deploy Agent      :8090   SERVER_ROLE=PRODUCTION, build TẮT
  ├─ PostgreSQL
  ├─ MESFlow (mesflow-app)  :8080
  └─ QA Center         :8095
""".strip("\n")

ARCHITECTURE_EXPLAIN = [
    {"term": "DEV", "text": "Máy đang sửa code + build package/image. Đây là nơi DUY NHẤT được phép build. "
                             "SERVER_ROLE=DEV, MESFLOW_BUILD_ENABLED=1, có workspace mount vào Deploy Agent."},
    {"term": "PRODUCTION TEST", "text": "Server test riêng, gần giống Production nhưng KHÔNG phải Production thật. "
                                          "Dùng để thử đúng artifact (đúng ZIP SHA256 / image digest) sẽ đưa lên "
                                          "Production, không bao giờ build lại ở đây."},
    {"term": "PRODUCTION", "text": "Máy chạy thật cho người dùng cuối. Chỉ nhận đúng artifact đã có TEST_PASS, và "
                                     "luôn cần con người bấm duyệt tường minh mỗi lần, không có ngoại lệ."},
    {"term": "Bootstrap", "text": "Dịch vụ độc lập, cổng 8098, không phụ thuộc Docker/MESFlow. Việc duy nhất: dựng "
                                    "máy Ubuntu trống (SSH + Docker) và cài/cứu hộ Deploy Agent. Đây là 'cửa vào' để "
                                    "phục hồi khi mọi thứ khác đã hỏng."},
    {"term": "Deploy Agent", "text": "Control plane triển khai + vận hành thật sự: build (chỉ trên DEV), upload, "
                                       "deploy --no-build, verify health/schema, rollback, quản lý MESFlow lẫn QA "
                                       "Center. Cổng 8090."},
]

# --------------------------------------------------------------------------
# 2. Server role — source of truth
# --------------------------------------------------------------------------
SERVER_ROLE = {
    "intro": "Vai trò của một server (DEV / PRODUCTION_TEST / PRODUCTION) KHÔNG được đoán từ hostname hay IP. "
             "Nó đến từ đúng một biến môi trường, <code>SERVER_ROLE</code>, được Deploy Agent đọc khi khởi động "
             "(<code>deploy-agent/agent.py</code>: <code>SERVER_ROLE = os.environ.get(\"SERVER_ROLE\",\"DEV\").strip().upper()</code>).",
    "canonical_values": ["DEV", "PRODUCTION_TEST", "PRODUCTION"],
    "how_set": "Biến này được set bằng cách Deploy Agent chạy <code>docker compose</code> với đúng 1 file override "
               "khớp vai trò thật của máy, cộng trên nền <code>compose.linux.yml</code> (nền này tự mặc định "
               "<code>SERVER_ROLE=PRODUCTION_TEST</code>, build tắt, nếu không có gì override — mặc định an toàn).",
    "compose_table": [
        {"host": "DEV local", "file": "docker/compose.dev.override.yml",
         "sets": "SERVER_ROLE=DEV, MESFLOW_BUILD_ENABLED=1, mount workspace vào /workspace/mesflow"},
        {"host": "Production Test", "file": "docker/compose.production-test.override.yml",
         "sets": "SERVER_ROLE=PRODUCTION_TEST, MESFLOW_BUILD_ENABLED=0"},
        {"host": "Production", "file": "docker/compose.production.override.yml",
         "sets": "SERVER_ROLE=PRODUCTION, MESFLOW_BUILD_ENABLED=0"},
        {"host": "Máy mới cài qua Bootstrap", "file": "docker/compose.bootstrap.override.yml",
         "sets": "chỉ bind port 127.0.0.1:8090:8090 — KHÔNG tự set vai trò"},
    ],
    "install_default": "Khi cài mới qua <code>deploy-agent/installer/install.sh</code> (kể cả qua Bootstrap → "
                        "Install Deploy Agent), installer tự dò: nếu biến môi trường <code>SERVER_ROLE</code> được "
                        "set tường minh thì dùng đúng giá trị đó; nếu không, nó chỉ chọn DEV khi máy này thật sự có "
                        "một workspace checkout hợp lệ (thư mục <code>deploy-agent/docker/compose.dev.override.yml</code> "
                        "tồn tại trong <code>MESFLOW_WORKSPACE_ROOT</code> đã resolve) — nếu không tìm thấy, mặc định "
                        "an toàn là <b>PRODUCTION_TEST</b>. Một server Production Test/Production mới toanh không có "
                        "workspace nên luôn rơi vào PRODUCTION_TEST theo mặc định; phải tự tay chuyển sang PRODUCTION "
                        "nếu đó thật sự là máy Production (xem lệnh bên dưới).",
    "verify_commands": [
        c(SERVER,
          "curl -fsS http://127.0.0.1:8090/agent/health | python3 -c \"import json,sys; d=json.load(sys.stdin); print('SERVER ROLE:', d['server_role'])\"",
          "Ví dụ kết quả thật lấy từ một máy DEV: SERVER ROLE: DEV"),
        c(SERVER,
          "docker inspect mesflow-deploy-agent --format '{{range .Config.Env}}{{println .}}{{end}}' | grep ^SERVER_ROLE=",
          "Đọc trực tiếp từ container đang chạy, không qua HTTP — dùng khi Deploy Agent không trả lời được /agent/health."),
    ],
    "fix_commands": [
        c(SERVER, "cd /opt/mesflow-deploy-agent/docker", "Thư mục compose thật trên server."),
        c(SERVER, "# DEV local:\ndocker compose -f compose.linux.yml -f compose.dev.override.yml "
                    "-f compose.bootstrap.override.yml up -d"),
        c(SERVER, "# Production Test:\ndocker compose -f compose.linux.yml "
                    "-f compose.production-test.override.yml up -d"),
        c(SERVER, "# Production:\ndocker compose -f compose.linux.yml "
                    "-f compose.production.override.yml up -d"),
    ],
    "warning": "KHÔNG BAO GIỜ deploy hay promote bất cứ thứ gì cho tới khi <code>server_role</code> hiển thị đúng "
               "với ý định thật của bạn. Đã có sự cố thật: cài lại Deploy Agent trên máy DEV qua Bootstrap từng "
               "lặng lẽ đổi máy DEV thành PRODUCTION_TEST (mất build + mất mount workspace) vì installer quên thêm "
               "compose.dev.override.yml — đã fix, nhưng luôn tự kiểm tra lại sau mỗi lần cài/update, không tin "
               "tưởng mù quáng.",
}

# --------------------------------------------------------------------------
# 3. The 12-step deployment journey
# --------------------------------------------------------------------------
STEPS: list[dict] = []

STEPS.append(step(
    "step-01", "01", "Chuẩn bị máy chủ",
    purpose="Xác nhận máy Ubuntu mới đủ điều kiện trước khi cài bất cứ thứ gì — hệ điều hành, tài nguyên, giờ hệ thống.",
    where="Trên server Ubuntu mới, qua console của nhà cung cấp hạ tầng hoặc một phiên SSH tạm thời ban đầu.",
    blocks=[
        block("Xác nhận hệ điều hành", [
            c(SERVER, "cat /etc/os-release"),
            c(SERVER, "uname -a"),
            c(SERVER, "hostnamectl"),
        ], note="Bootstrap hỗ trợ và đã kiểm thử trên Ubuntu (<code>install.sh</code> tự phát hiện "
                "<code>ID=ubuntu</code> trong <code>/etc/os-release</code>; hệ điều hành khác vẫn chạy được nhưng "
                "chỉ in cảnh báo, không được kiểm thử chính thức)."),
        block("Xác nhận địa chỉ mạng", [c(SERVER, "hostname -I")]),
        block("Kiểm tra tài nguyên", [
            c(SERVER, "free -h"),
            c(SERVER, "df -h"),
            c(SERVER, "lsblk"),
        ], note="Cấu hình CPU/RAM/disk tối thiểu — <b>chưa được quy định chính thức</b> trong workspace hiện tại; "
                "không có tài liệu nào trong <code>docs/</code> nêu con số cụ thể. Đừng tin bất kỳ con số nào không "
                "trích được từ code/docs thật — ước lượng thực tế theo tải: PostgreSQL + MESFlow + QA Center + "
                "Deploy Agent chạy đồng thời trên cùng một máy."),
        block("Kiểm tra giờ hệ thống", [c(SERVER, "timedatectl")],
              note="MESFlow kỳ vọng timezone <code>Asia/Ho_Chi_Minh</code>. Nếu khác, đặt lại:"),
        block("Đặt timezone (nếu cần)", [c(SERVER, "sudo timedatectl set-timezone Asia/Ho_Chi_Minh")]),
    ],
    expected="<code>ID=ubuntu</code> trong /etc/os-release; đủ RAM/disk trống cho khối lượng dự kiến; "
             "<code>Time zone: Asia/Ho_Chi_Minh</code> trong timedatectl.",
    on_error="Không phải Ubuntu → cân nhắc cài lại OS trước khi tiếp tục; Bootstrap chỉ cảnh báo chứ không chặn, "
             "nhưng chạy ngoài Ubuntu là chưa được kiểm thử. Sai timezone → chạy lệnh set-timezone ở trên rồi kiểm "
             "tra lại.",
    next_="Bước 02 — Kết nối SSH",
))

STEPS.append(step(
    "step-02", "02", "Kết nối SSH",
    purpose="Thiết lập kết nối SSH ổn định, có alias, từ máy DEV/laptop của bạn tới server mới — mọi bước sau đều "
            "cần kết nối này.",
    where="Trên máy DEV/laptop của quản trị viên.",
    blocks=[
        block("Kết nối trực tiếp lần đầu", [c(DEV, "ssh ubuntu@<SERVER_IP>")],
              note="Thay <code>ubuntu</code> bằng user thật trên server, <code>&lt;SERVER_IP&gt;</code> bằng IP thật."),
        block("Tạo alias để không phải gõ lại thông tin mỗi lần", [
            c(DEV, "mkdir -p ~/.ssh && ${EDITOR:-nano} ~/.ssh/config",
              "Thêm khối cấu hình dưới đây vào cuối file."),
        ], text="~/.ssh/config\n\nHost mesflow-test\n    HostName &lt;SERVER_IP&gt;\n    User ubuntu\n"
                "    IdentityFile ~/.ssh/&lt;key&gt;\n"),
        block("Dùng alias", [
            c(DEV, "ssh mesflow-test"),
        ], note="Trong workspace này, alias thật cho server test là <code>mesflow-test</code> — xem "
                "<code>../AGENTS.md</code>."),
        block("Chép file / thư mục qua SSH", [
            c(DEV, "scp -r <thư_mục_local> mesflow-test:/tmp/<đích>"),
            c(DEV, "rsync -avz <thư_mục_local>/ mesflow-test:/tmp/<đích>/"),
        ], note="scp đơn giản cho lần chép đầu; rsync hiệu quả hơn cho lần chép lại (chỉ gửi phần thay đổi)."),
    ],
    expected="<code>ssh mesflow-test</code> vào thẳng server không hỏi lại thông tin (ngoài passphrase khoá, nếu có).",
    on_error="Connection refused/timeout → SSH chưa chạy trên server hoặc firewall/nhà cung cấp chặn cổng 22 — "
             "kiểm tra qua console nhà cung cấp. Permission denied → sai user/khoá — xác nhận lại "
             "<code>IdentityFile</code> và user trong <code>~/.ssh/config</code>.",
    next_="Bước 03 — Chép Bootstrap lên server",
))

STEPS.append(step(
    "step-03", "03", "Chép Bootstrap lên server",
    purpose="Đưa mã nguồn Bootstrap (chưa cài gì cả — chỉ chép file) lên server mới để chuẩn bị chạy installer.",
    where="Bắt đầu trên máy DEV, kết thúc trên server.",
    blocks=[
        block("Chép thư mục bootstrap/ sang server", [
            c(DEV, "cd ~/workspace/mesflow"),
            c(DEV, "scp -r bootstrap mesflow-test:/tmp/mesflow-bootstrap"),
        ], note="<code>~/workspace/mesflow/bootstrap</code> là vị trí nguồn chính thức hiện tại của Bootstrap trong "
                "workspace này."),
        block("Vào server và kiểm tra file đã chép", [
            c(SERVER, "ssh mesflow-test"),
            c(SERVER, "ls -la /tmp/mesflow-bootstrap"),
            c(SERVER, "cd /tmp/mesflow-bootstrap"),
        ]),
    ],
    expected="Thư mục /tmp/mesflow-bootstrap trên server chứa đúng: <code>install.sh</code>, <code>app.py</code>, "
             "<code>guide_content.py</code>, <code>requirements.txt</code>, <code>templates/</code>, "
             "<code>static/</code>, <code>README.md</code>, <code>VERSION.txt</code>.",
    on_error="Thiếu file (đặc biệt <code>install.sh</code> hoặc <code>app.py</code>) → chép lại từ đầu, kiểm tra "
             "lệnh scp không bị lỗi giữa chừng (hết dung lượng, mất kết nối).",
    next_="Bước 04 — Cài Bootstrap",
))

STEPS.append(step(
    "step-04", "04", "Cài Bootstrap",
    purpose="Chạy installer để cài đặt môi trường tối thiểu (OpenSSH, Docker Engine + Compose) và khởi động dịch vụ "
            "web Bootstrap dưới systemd.",
    where="Trên server, trong thư mục vừa chép ở Bước 03.",
    blocks=[
        block("Chạy installer", [c(SERVER, "sudo bash install.sh")],
              note="<b>Những gì install.sh thực sự làm</b> (đọc trực tiếp từ code, không phải suy đoán):"),
        block("", text="1. Phát hiện Ubuntu (chỉ cảnh báo nếu không phải Ubuntu, không chặn).\n"
                        "2. Cài openssh-server nếu chưa có, bật + enable dịch vụ ssh.\n"
                        "3. Cài Docker Engine + Compose plugin từ get.docker.com nếu chưa có Docker; tạo Docker "
                        "network mesflow-edge nếu chưa tồn tại (Deploy Agent's compose cần network này, khai báo "
                        "external: true).\n"
                        "4. Tạo /opt/mesflow-bootstrap (code + venv) và /var/lib/mesflow-bootstrap (dữ liệu bền "
                        "vững: tài khoản admin, log, state) — KHÔNG bao giờ tạo/xoá /var/lib/mesflow-deploy-agent.\n"
                        "5. Vendor một bản sao KHÔNG chỉnh sửa của deploy-agent/updater/updater.py vào "
                        "agent_updater_core.py, cho khả năng Update/Rollback của Deploy Agent sau này.\n"
                        "6. Tạo virtualenv Python, cài Flask + waitress.\n"
                        "7. Cài & khởi động systemd service mesflow-bootstrap.service (không require docker.service "
                        "hay bất kỳ unit MESFlow nào — Bootstrap phải sống được cả khi Docker/MESFlow/Deploy Agent "
                        "đang chết).\n"
                        "8. Poll http://127.0.0.1:8098/health tới 15 lần, mỗi lần cách 1 giây, để xác nhận healthy.\n"
                        "Idempotent: chạy lại install.sh không mất tài khoản admin/log/state đã có."),
        block("Xác nhận dịch vụ đã chạy", [
            c(SERVER, "sudo systemctl status mesflow-bootstrap --no-pager"),
            c(SERVER, "curl -fsS http://127.0.0.1:8098/health"),
            c(SERVER, "sudo ss -ltnp | grep ':8098'"),
        ]),
    ],
    expected="systemctl status → active (running); curl /health → <code>{\"ok\": true, \"service\": "
             "\"mesflow-bootstrap\", ...}</code>; ss -ltnp cho thấy có tiến trình lắng nghe cổng 8098.",
    on_error="install.sh thoát với lỗi → đọc thông báo ERROR: cụ thể (script dùng <code>set -Eeuo pipefail</code>, "
             "dừng ngay khi có lỗi). Healthy timeout sau 15 giây → "
             "<code>journalctl -u mesflow-bootstrap -n 100</code> để xem log khởi động.",
    next_="Bước 05 — Truy cập Bootstrap Web",
))

STEPS.append(step(
    "step-05", "05", "Truy cập Bootstrap Web",
    purpose="Mở giao diện Bootstrap từ trình duyệt trên laptop của bạn — server không có desktop, nên phải dùng SSH "
            "tunnel thay vì mở trình duyệt trực tiếp trên server.",
    where="Server không cần desktop environment. Trình duyệt chạy trên laptop; đường nối là SSH tunnel.",
    blocks=[
        block("Mở tunnel từ laptop", [
            c(DEV, "ssh -N \\\n  -L 18098:127.0.0.1:8098 \\\n  mesflow-test",
              "Giữ terminal này mở — tunnel chỉ sống khi lệnh này còn chạy."),
        ]),
        block("Mở trình duyệt", [c(BROWSER, "http://127.0.0.1:18098/")]),
        block("Vì sao dùng cổng 18098 ở local thay vì 8098?",
              text="Cổng 8098 có thể đã bị chiếm trên chính máy DEV (ví dụ máy DEV cũng đang chạy Bootstrap của "
                   "riêng nó). Map sang một cổng local khác (18098) tránh xung đột mà không đổi gì trên server."),
        block("Sơ đồ", text="Chrome (laptop)\n127.0.0.1:18098\n      │\n      │ SSH tunnel\n      ▼\nserver\n"
                             "127.0.0.1:8098\nBootstrap"),
    ],
    expected="Trình duyệt trên laptop mở được trang đăng nhập/setup của Bootstrap tại 127.0.0.1:18098.",
    on_error="Trình duyệt không kết nối được → kiểm tra terminal chạy lệnh ssh -N còn sống, chưa bị Ctrl+C. "
             "\"bind: address already in use\" → cổng 18098 trên laptop đã bị chiếm, đổi sang cổng khác "
             "(vd 18099) ở cả hai phía lệnh -L VÀ URL trình duyệt.",
    next_="Bước 06 — Xác định vai trò server",
))

STEPS.append(step(
    "step-06", "06", "Xác định vai trò server",
    purpose="Trước khi đi tiếp, xác nhận tường minh máy này là DEV, PRODUCTION_TEST hay PRODUCTION — không đoán.",
    where="Trên server, qua SSH (Deploy Agent chưa cài ở bước này thì mục này sẽ trả về 'chưa cài').",
    blocks=[
        block("Kiểm tra (nếu Deploy Agent đã cài)", SERVER_ROLE["verify_commands"]),
        block("Nếu Deploy Agent CHƯA cài",
              text="Chưa có gì để kiểm tra — vai trò sẽ được xác lập ở Bước 07 khi cài Deploy Agent. Ghi nhớ trước: "
                   "vai trò DỰ ĐỊNH của máy này là gì (DEV / PRODUCTION_TEST / PRODUCTION), vì mặc định cài mới cho "
                   "một máy không có workspace luôn là PRODUCTION_TEST."),
    ],
    expected="Biết chắc và ghi nhớ: SERVER ROLE dự định cho máy này.",
    on_error="Xem toàn bộ chi tiết & cách sửa vai trò sai ở phần 'Vai trò server (SERVER_ROLE)' phía trên các bước.",
    next_="Bước 07 — Cài Deploy Agent",
))

STEPS.append(step(
    "step-07", "07", "Cài Deploy Agent",
    purpose="Build package Deploy Agent trên DEV, đưa lên server qua Bootstrap (hoặc cài trực tiếp qua SSH), rồi "
            "xác minh healthy.",
    where="Build trên DEV; cài đặt trên server (qua Bootstrap Web hoặc SSH trực tiếp).",
    blocks=[
        block("1) Build package trên DEV — Bootstrap KHÔNG tự build Deploy Agent", [
            c(DEV, "cd ~/workspace/mesflow/deploy-agent"),
            c(DEV, "./package_installer.sh",
              "Mặc định TỰ TĂNG version (scripts/bump-version.sh) rồi đóng gói — mỗi lần chạy ra một package mới, "
              "không bao giờ trùng version cũ. Dùng --no-bump để đóng gói đúng VERSION.txt hiện tại, hoặc --to "
              "&lt;version&gt; để nhảy tới version cụ thể."),
        ], note="Kết quả: <code>artifacts/deploy-agent/MESFlow_Server_Bootstrap_Agent_First_v&lt;VERSION&gt;.zip</code> "
                "— gồm <code>install.sh</code> ở gốc + <code>payload/mesflow-deploy-agent/{agent.py, VERSION.txt, "
                "docker/...}</code>. <b>Luật bất biến:</b> một version chỉ được release một lần — không bao giờ tái "
                "sử dụng version đã release."),
        block("2A) Cài qua Bootstrap Web (khuyến nghị)",
              text="Bootstrap → Install Deploy Agent → chọn file .zip vừa build → (tuỳ chọn) dán SHA256 để Bootstrap "
                   "tự đối chiếu → Validate & Install.\n\n"
                   "Bootstrap sẽ: xác thực cấu trúc ZIP đúng install.sh + payload/mesflow-deploy-agent/{agent.py, "
                   "VERSION.txt}, đọc VERSION.txt, chặn downgrade trừ khi tick 'Allow downgrade', chạy đúng "
                   "install.sh của package (y hệt một người vận hành gõ tay qua SSH — Bootstrap không tự cài đặt "
                   "logic build/rollback riêng), rồi tự poll http://127.0.0.1:8090/agent/health và báo PASS/FAILED."),
        block("2B) Cài trực tiếp qua SSH (cách dự phòng dòng lệnh)", [
            c(DEV, "scp artifacts/deploy-agent/MESFlow_Server_Bootstrap_Agent_First_v<VERSION>.zip mesflow-test:/tmp/"),
            c(SERVER, "cd /tmp && unzip MESFlow_Server_Bootstrap_Agent_First_v<VERSION>.zip"),
            c(SERVER, "cd MESFlow_Server_Bootstrap_Agent_First_v<VERSION>"),
            c(SERVER, "sudo bash install.sh"),
        ], note="Đây chính là <code>deploy-agent/installer/install.sh</code> thật — không có API upload riêng nào "
                "khác ngoài form web ở 2A và chạy trực tiếp script này; đừng bịa ra một API không tồn tại."),
        block("Về /opt/mesflow/.env — điều kiện bắt buộc trước khi cài",
              text="installer từ chối chạy nếu <code>/opt/mesflow/.env</code> chưa tồn tại (file này chứa secret, "
                   "installer không tự tạo hay copy nó). Một người phải tạo/copy file này thủ công lên server TRƯỚC "
                   "khi cài Deploy Agent."),
    ],
    expected="Kết quả PASS trên Bootstrap (hoặc install.sh in ra JSON health cuối cùng khi cài qua SSH).",
    on_error="'Missing persistent /opt/mesflow/.env' → tạo file đó trước, xem ghi chú ở trên. VERSION_ALREADY_RELEASED "
             "khi build → tăng version rồi build lại, không bao giờ ép ghi đè. Health không lên sau 15 lần poll → "
             "installer tự rollback về image cũ (nếu có) — kiểm tra <code>docker logs mesflow-deploy-agent</code>.",
    next_="Bước 08 — Kiểm tra Docker/services",
))

STEPS.append(step(
    "step-08", "08", "Kiểm tra Docker/services",
    purpose="Xác minh Deploy Agent thật sự khoẻ mạnh và đọc đúng các trường quan trọng trong health trước khi deploy "
            "bất cứ ứng dụng nào lên đây.",
    where="Trên server.",
    blocks=[
        block("Health đầy đủ", [
            c(SERVER, "curl -fsS http://127.0.0.1:8090/agent/health | python3 -m json.tool"),
        ]),
        block("Container & cổng", [
            c(SERVER, "docker ps --filter name=mesflow-deploy-agent"),
            c(SERVER, "sudo ss -ltnp | grep ':8090'"),
        ]),
        block("Các trường quan trọng trong health (ví dụ thật, lấy từ một máy DEV)",
              text="agent_version   \"2.24.8-docker-runtime\"\n"
                   "server_role     \"DEV\"                    ← xác nhận đúng ý định (Bước 06)\n"
                   "build_enabled   true                        ← DEV: true, Test/Production: false\n"
                   "deploy_enabled  true\n"
                   "mes.docker.available   true\n"
                   "mes.docker.healthy     true\n"
                   "mes.online             true\n"
                   "qa.online              true"),
    ],
    expected="ok: true, server_role đúng ý định, docker ps thấy container mesflow-deploy-agent đang Up.",
    on_error="ok: false hoặc curl connection refused → xem mục 'Sự cố thường gặp — DEPLOY AGENT OFFLINE' phía dưới.",
    next_="Bước 09 — Deploy MESFlow",
))

STEPS.append(step(
    "step-09", "09", "Deploy MESFlow",
    purpose="Build MỘT LẦN trên DEV, deploy local để lấy LOCAL_PASS, promote đúng artifact đó (cùng SHA/digest) sang "
            "Production Test, lấy TEST_PASS, rồi mới cân nhắc Production — không bao giờ build lại giữa các môi trường.",
    where="Build trên DEV. Promote/deploy thao tác qua Deploy Agent Web (SSH tunnel cổng 18090) trên từng máy đích.",
    blocks=[
        block("Thứ tự triển khai cho một server hoàn toàn mới",
              text="1. Bootstrap  (Bước 04)\n2. Deploy Agent  (Bước 07)\n3. PostgreSQL — do compose của MESFlow tự "
                   "tạo khi deploy, KHÔNG cần khởi tạo tay\n4. MESFlow (mesflow-app)\n5. nginx/gateway — nếu compose "
                   "hiện tại của bạn có bao gồm; kiểm tra trực tiếp compose đang dùng trên máy đó, đừng giả định\n"
                   "6. QA Center (Bước 10)\n\n"
                   "PostgreSQL không cần thao tác thủ công riêng: nó nằm trong compose mà Deploy Agent triển khai "
                   "cùng MESFlow (thấy trong health thật: mes.docker.container_ids.postgres, "
                   "mes.docker.service_health.postgres)."),
        block("A. Build Release trên DEV",
              text="Deploy Agent Web (DEV) → Release & Deploy → Build Release. Chạy scripts/build-release.sh, tạo "
                   "image bất biến mesflow-app:&lt;version&gt; (gắn tag VÀ định danh bằng digest) + ZIP dưới "
                   "artifacts/releases/&lt;version&gt;/, đóng băng: version, source_commit, package sha256 "
                   "(checksums.txt), image_digest, expected_schema_revision (release.json). Bị chặn nếu "
                   "MESFLOW_BUILD_ENABLED=0 (không phải máy DEV) — đúng như thiết kế."),
        block("B. Deploy Local (trên chính DEV) → LOCAL_PASS",
              text="Release & Deploy → Deploy Local. Deploy --no-build đúng image vừa build (theo digest, không "
                   "phải theo tag). LOCAL_PASS được tính từ bằng chứng thật, không phải return code: image id đang "
                   "chạy phải khớp release đã đóng băng, Alembic head thật (/api/system/ready → migration_head) "
                   "phải khớp expected_schema_revision, và một smoke check HTTP tới /login phải thành công."),
        block("C. Promote Production Test → TEST_PASS",
              text="Release & Deploy → Promote Production Test.\n\nTRƯỚC KHI bấm: xác nhận health của Production "
                   "Test (Bước 08 lặp lại trên máy Test) VÀ server_role của Production Test PHẢI đúng "
                   "PRODUCTION_TEST.", ),
        block("", commands=[
            c(SERVER, "curl -fsS http://127.0.0.1:8090/agent/health | grep -o '\"server_role\":\"[^\"]*\"'",
              "Chạy trên máy Production Test — kết quả bắt buộc: \"server_role\":\"PRODUCTION_TEST\""),
        ]),
        block("",
              text="Cần LOCAL_PASS cho đúng version + Agent DEV đã cấu hình "
                   "MESFLOW_PRODUCTION_TEST_AGENT_URL/_USER/_PASSWORD. Deploy Agent upload đúng ZIP đã LOCAL_PASS, "
                   "kích hoạt --no-build trên máy đích, poll tới khi xong, ghi nhận TEST_PASS."),
        block("⚠ NGỪNG NGAY nếu vai trò máy đích không khớp",
              text="Nếu curl ở trên KHÔNG trả về đúng PRODUCTION_TEST cho máy Production Test — DỪNG LẠI. Không "
                   "upload, không deploy. Sửa vai trò trước (phần 'Vai trò server' → mục fix), xác minh lại, rồi "
                   "mới tiếp tục."),
        block("D. Production Deploy — CẦN PHÊ DUYỆT NGƯỜI, MỖI LẦN",
              text="Release & Deploy → Promote Production. Endpoint này tự kiểm tra lại toàn bộ điều kiện mỗi lần "
                   "gọi (LOCAL_PASS + TEST_PASS + đúng zip sha + đúng image digest + schema PASS + không bị "
                   "contaminated), trả về 403 trừ khi Agent được bật MESFLOW_PRODUCTION_PROMOTE_ENABLED=1 VÀ request "
                   "có {\"confirm\": true} tường minh — và ngay cả khi đủ điều kiện, endpoint này trong bản Agent "
                   "hiện tại chỉ trả về 501 (chưa thật sự thực thi deploy Production — mới dừng ở phần đấu dây/"
                   "kiểm tra điều kiện). Không có đường tắt tự động nào deploy Production."),
    ],
    expected="Pipeline status trên Deploy Agent Web hiện đúng chuỗi: BUILT → LOCAL_PASS → TEST_PASS, với lý do rõ "
             "ràng bất cứ khi nào một nút bị mờ.",
    on_error="LOCAL_PASS bị BLOCKED với lý do QA_RUNNER_UNAVAILABLE → không phải bug, chỉ là QA Center tạm thời "
             "không resolve được trên mạng Docker — đợi QA Center khoẻ lại rồi bấm lại Deploy Local (idempotent). "
             "'No release has been built yet' dù artifacts/releases/&lt;version&gt; có thật trên máy → kiểm tra lại "
             "mount workspace + server_role=DEV (Bước 06).",
    next_="Bước 10 — Deploy QA Center",
))

STEPS.append(step(
    "step-10", "10", "Deploy QA Center",
    purpose="QA Center là một release ĐỘC LẬP với MESFlow — build riêng, version riêng, nhưng deploy qua cùng Deploy "
            "Agent với luồng tương tự.",
    where="Build trên DEV (trong chính QA Center hoặc trong Deploy Agent); deploy qua Deploy Agent Web.",
    blocks=[
        block("Sửa file nào trước khi build version mới",
              text="qa-center/current/VERSION — version nguồn.\nqa-center/current/agent.py — APP_VERSION PHẢI khớp "
                   "CHÍNH XÁC với VERSION, nếu không build bị chặn VERSION_MISMATCH."),
        block("Hai nơi có thể bấm Build — cùng ra một kết quả",
              text="1. Trong chính QA Center: trang Release Package (chỉ hiện khi chạy trực tiếp từ workspace, "
                   "không có trong image đã đóng gói) → Build Release ZIP → chạy nền, poll trạng thái → Download "
                   "ZIP để tự tay upload lên Deploy Agent.\n"
                   "2. Trong Deploy Agent: tab QA Center → Build Release (POST /api/qa-release-manager/build) — gọi "
                   "đúng qa-center/scripts/build-release.sh, không phải bản build riêng."),
        block("Kết quả build", text="artifacts/qa-center/releases/&lt;version&gt;/QACenter_&lt;version&gt;.deploy.zip, kèm "
                                     "manifest.json (version, source commit, previous release, changed files, diff "
                                     "stat, artifact SHA256), CHANGELOG.md, checksums.txt, BUILD_REPORT.md."),
        block("Deploy", text="Trong Deploy Agent, sau build có thể Deploy Local / Promote Production Test ngay — "
                              "bám sát luồng của MESFlow. Deploy Agent nhận QA ZIP qua POST /qa-release/upload, "
                              "verify checksum + image digest, rồi POST /qa-release/deploy/&lt;version&gt; mới thật sự "
                              "deploy — không có bước nào tự động deploy chỉ vì đã upload."),
        block("Luật bất biến version — giống hệt MESFlow",
              text="Nếu build báo VERSION_ALREADY_RELEASED: version đó đã đóng băng, không sửa được — tăng "
                   "qa-center/current/VERSION (và APP_VERSION khớp theo) rồi build lại. Không bao giờ ghi đè "
                   "metadata release đã đóng băng."),
    ],
    expected="QA Center container chạy khoẻ, /agent/health của Deploy Agent báo qa.online: true.",
    on_error="VERSION_MISMATCH → đồng bộ lại VERSION và APP_VERSION cho khớp tuyệt đối rồi build lại.",
    next_="Bước 11 — Kiểm tra sau deploy",
))

STEPS.append(step(
    "step-11", "11", "Kiểm tra sau deploy",
    purpose="Xác nhận toàn bộ hệ thống thật sự hoạt động, không chỉ dừng ở 'lệnh deploy chạy xong không lỗi'.",
    where="Trên server vừa deploy, và trình duyệt qua SSH tunnel để kiểm tra ứng dụng.",
    blocks=[
        block("Containers & dịch vụ", [
            c(SERVER, "docker ps"),
            c(SERVER, "curl -fsS http://127.0.0.1:8090/agent/health | python3 -m json.tool"),
        ]),
        block("Health từng thành phần (đọc trong JSON /agent/health ở trên)",
              text="mes.online, mes.docker.healthy, mes.health_payload.status\n"
                   "mes.health_payload.postgres_version, mes.docker.service_health.postgres\n"
                   "qa.online, qa.payload.ok"),
        block("Log khi cần soi kỹ hơn", [
            c(SERVER, "docker logs --tail=200 mesflow-deploy-agent"),
            c(SERVER, "docker logs --tail=200 <container_mesflow_hoặc_qa>"),
        ]),
        block("Kiểm tra ứng dụng qua trình duyệt (qua tunnel Bước 05/15)",
              text="Đăng nhập → Dashboard → tạo/xem một Production Order → mở một Session → (nếu áp dụng) kiosk → "
                   "QA Center. Đây là bước xác nhận thật sự bằng mắt, không chỉ dựa vào health JSON."),
    ],
    expected="Mọi container Up, mes.health_payload.status = healthy, đăng nhập + các trang chính mở được không lỗi.",
    on_error="Xem mục 'Sự cố thường gặp' và 'Recovery flow' phía dưới — đi theo đúng thứ tự chẩn đoán, không nhảy "
             "cóc.",
    next_="Bước 12 — Recovery / xử lý lỗi (khi có sự cố)",
))

STEPS.append(step(
    "step-12", "12", "Recovery / xử lý lỗi",
    purpose="Khi có sự cố, đi theo đúng cây quyết định thay vì đoán mò — mỗi câu trả lời NO dẫn tới đúng hành động "
            "kế tiếp.",
    where="Tuỳ tầng gặp sự cố — bắt đầu luôn từ SSH.",
    blocks=[
        block("Xem chi tiết đầy đủ ở hai mục cuối trang", text="'Sự cố thường gặp' (triệu chứng → nguyên nhân → "
                                                                  "cách xử lý) và 'Cây quyết định phục hồi' (theo "
                                                                  "từng câu hỏi Có/Không) được trình bày riêng bên "
                                                                  "dưới trang này để dễ tra cứu lại sau, không lặp "
                                                                  "lại ở đây."),
    ],
    expected="Xác định đúng tầng đang lỗi và hành động đúng cho tầng đó, không đoán mò/không chạy lệnh phá huỷ dữ liệu.",
    on_error="Nếu không chắc chắn nguyên nhân → DỪNG LẠI, không chạy lệnh phá huỷ (không prune, không xoá volume, "
             "không DROP/TRUNCATE) — ghi lại triệu chứng thật và log liên quan trước khi thử bất cứ hành động sửa nào.",
    next_="Hoàn tất — quay lại Checklist trạng thái cuối trang để xác nhận đầy đủ.",
))

# --------------------------------------------------------------------------
# 4. Common failures
# --------------------------------------------------------------------------
FAILURES = [
    {
        "title": "PORT ĐÃ BỊ CHIẾM (port already in use)",
        "symptom": "docker start mesflow-app\n→ failed to bind 127.0.0.1:8080: address already in use",
        "diagnose": [c(SERVER, "sudo ss -ltnp | grep ':8080'"), c(SERVER, "docker ps --format "
                     "'table {{.Names}}\\t{{.Ports}}\\t{{.Status}}'")],
        "fix": "Xác định tiến trình/container nào đang giữ cổng đó trước khi làm bất cứ gì — có thể là một container "
               "cũ chưa dừng hẳn, hoặc một dịch vụ khác trên máy. Dừng đúng cái đang giữ cổng sai, không đoán mò.",
    },
    {
        "title": "CONTAINER BỊ DỪNG",
        "symptom": "docker ps -a  → container ở trạng thái Exited",
        "diagnose": [c(SERVER, "docker ps -a")],
        "fix": "Bootstrap → Docker (nút Start cho mesflow-deploy-agent), hoặc trong Deploy Agent Web → trang "
               "Services/Dịch vụ tương ứng để Start container đó. Không tự ý docker rm rồi tạo lại thủ công.",
    },
    {
        "title": "HẾT DUNG LƯỢNG ĐĨA",
        "symptom": "df -h cho thấy /  gần đầy hoặc đầy",
        "diagnose": [c(SERVER, "df -h"), c(SERVER, "docker system df")],
        "fix": "KHÔNG tự động chạy prune phá huỷ (docker system prune -a, docker volume prune...). Xem release "
               "retention: Deploy Agent tự dọn release cũ (giữ mặc định 3 bản gần nhất) sau mỗi LOCAL_PASS/TEST_PASS "
               "thành công, có thể kích hoạt thủ công qua POST /api/release-manager/cleanup-releases. Với dữ liệu "
               "khác (log, backup...), xác nhận với người có thẩm quyền trước khi xoá.",
    },
    {
        "title": "RAM CAO",
        "symptom": "free -h cho thấy RAM khả dụng thấp",
        "diagnose": [c(SERVER, "free -h"), c(SERVER, "docker stats --no-stream")],
        "fix": "Xác định container nào chiếm nhiều nhất qua docker stats trước khi hành động — đừng restart hàng "
               "loạt. Nếu là rò rỉ bộ nhớ nghi vấn, thu log rồi báo cáo thay vì tự khởi động lại Production.",
    },
    {
        "title": "DEPLOY AGENT OFFLINE",
        "symptom": "curl http://127.0.0.1:8090/agent/health → connection refused",
        "diagnose": [c(SERVER, "docker ps --filter name=mesflow-deploy-agent"),
                     c(SERVER, "docker logs --tail=200 mesflow-deploy-agent")],
        "fix": "Bootstrap Overview đã tự phát hiện tình trạng này (badge 'Deploy Agent Stopped'/'Unhealthy'/'Not "
               "Installed') và hiện đúng nút hành động: Start/Restart, hoặc Install Deploy Agent nếu chưa từng cài. "
               "Nếu vẫn không lên, dùng Bootstrap → Install Deploy Agent để reinstall/update package.",
    },
    {
        "title": "QUÊN MẬT KHẨU (Bootstrap / Deploy Agent / MESFlow)",
        "symptom": "Không đăng nhập được vào Bootstrap Web, Deploy Agent Web, hoặc ứng dụng MESFlow.",
        "diagnose": [],
        "fix": "Xem mục riêng '<b>Khôi phục truy cập / Quên mật khẩu</b>' ngay bên dưới trang này — mỗi hệ thống có "
               "cơ chế khôi phục khác nhau, trình bày đầy đủ theo từng bước ở đó thay vì lặp lại ở đây.",
    },
    {
        "title": "LỆNH `reset-admin` BÁO \"unknown command\"",
        "symptom": "docker exec mesflow-app python -m mesflow.cli reset-admin\n"
                   "→ unknown command",
        "diagnose": [
            c(MESFLOW_SERVER, 'docker exec mesflow-app grep -o "funcs={[^}]*}" /app/mesflow/cli.py',
              "Đọc thẳng danh sách lệnh CLI thật đang có trong image đang chạy — đã xác minh trực tiếp trên một "
              "host DEV thật lúc viết mục này, kết quả chỉ có: wait-db, seed-admin, seed-default-users, "
              "reset-admin, verify-schema, record-deployment, run-predictive."),
        ],
        "fix": "KHÔNG đoán/thử một subcommand khác. Chỉ dùng đúng tên lệnh xuất hiện trong kết quả grep ở trên — "
               "danh sách lệnh CÓ THỂ khác nhau giữa các version MESFlow, nên luôn kiểm tra lại trên chính host "
               "đang thao tác thay vì tin vào tài liệu cũ (kể cả trang này) mà không xác minh. Nếu <code>reset-admin</code> "
               "không xuất hiện, image đang chạy là một bản MESFlow khác/cũ hơn những gì trang này mô tả — dừng lại "
               "và xác nhận version trước khi tiếp tục, đừng thử lệnh khác 'cho chắc'.",
    },
    {
        "title": "mesflow-app KHÔNG CHẠY (docker exec không vào được)",
        "symptom": "docker exec mesflow-app ...\n"
                   "→ Error: No such container: mesflow-app",
        "diagnose": [c(MESFLOW_SERVER, "docker ps -a --filter name=mesflow-app",
                       "Xem trạng thái thật: không tồn tại, Exited, hay Restarting.")],
        "fix": "Nếu container tồn tại nhưng đang dừng: khởi động lại đúng container đó qua Deploy Agent (Docker/"
               "Services) trước, rồi mới thử lại <code>reset-admin</code> — <code>docker exec</code> chỉ hoạt động "
               "trên container đang chạy. KHÔNG tự ý <code>docker compose down -v</code> hay tạo lại database chỉ "
               "vì không exec được — đó là hai việc không liên quan tới nhau, và lệnh <code>-v</code> xoá volume dữ "
               "liệu thật.",
    },
    {
        "title": "BOOTSTRAP OFFLINE",
        "symptom": "curl http://127.0.0.1:8098/health không phản hồi",
        "diagnose": [c(SERVER, "sudo systemctl status mesflow-bootstrap")],
        "fix": "Bootstrap chạy dưới systemd, độc lập với Docker — nếu service không active:",
        "extra_commands": [
            c(SERVER, "sudo systemctl restart mesflow-bootstrap"),
            c(SERVER, "journalctl -u mesflow-bootstrap -n 100 --no-pager"),
        ],
    },
]

# --------------------------------------------------------------------------
# 4b. Khôi phục truy cập / Quên mật khẩu — Bootstrap, Deploy Agent, MESFlow
#
# Every command below was read from the current real implementation, not
# invented:
#   Bootstrap    -- bootstrap/app.py's load_state()/save_state() (no reset
#                    mechanism existed before this section; bin/reset-admin-
#                    password + bin/reset_admin_password.py were added
#                    alongside this guide section specifically to give it
#                    one -- see bootstrap/AGENTS.md).
#   Deploy Agent -- deploy-agent/agent.py: ensure_config(), _set_password(),
#                    _is_local_reset_request(), the /login, /forgot-password,
#                    /local-reset routes, and MESFLOW_AGENT_ADMIN_PASSWORD's
#                    exact overwrite-on-recreate behavior; deploy-agent/
#                    reset_password.py as the documented CLI fallback.
#   MESFlow      -- mesflow/app/mesflow/cli.py's reset_admin() (pre-existing,
#                    upsert, admin-only) and the new reset_password()
#                    (added alongside this guide section: looks up an
#                    EXISTING username, calls UserRepository.set_password()
#                    only -- role/active untouched -- and records
#                    audit_logs action ADMIN_PASSWORD_RESET).
# --------------------------------------------------------------------------
def access_card(system: str, if_forgotten: str, access_required: str, commands: list[dict],
                 expected: str, do_not: str, verify: list[dict] | str) -> dict:
    return {
        "system": system, "if_forgotten": if_forgotten, "access_required": access_required,
        "commands": commands, "expected": expected, "do_not": do_not, "verify": verify,
    }


RECOVERY_ACCESS = [
    access_card(
        "Bootstrap",
        if_forgotten="Chạy script reset cục bộ ngay trên server — không có, và sẽ không có, đường web nào để tự "
                      "reset (nếu bạn còn đăng nhập được vào Bootstrap Web thì bạn vốn không cần script này; xem "
                      "<code>bootstrap/AGENTS.md</code>: đây là quyết định thiết kế cố định, không phải thiếu sót).",
        access_required="SSH vào server + quyền <code>sudo</code>/root (đúng quyền <code>install.sh</code> đã yêu "
                          "cầu, không hơn).",
        commands=[
            c(DEV, "ssh mesflow-test"),
            c(SERVER, "sudo /opt/mesflow-bootstrap/bin/reset-admin-password",
              "Hỏi mật khẩu mới hai lần (không hiện lên màn hình), có thể đổi cả username bằng "
              "<code>--username &lt;tên_mới&gt;</code>. Chỉ ghi đè đúng hai trường "
              "<code>admin_username</code>/<code>admin_password_hash</code> trong "
              "<code>state.json</code> — mọi thứ khác (secret_key, agent_updater_token, setup_complete, ...) giữ "
              "nguyên."),
        ],
        expected="In ra <code>OK: đã đặt lại mật khẩu cho '&lt;username&gt;'.</code> Không cần restart "
                 "<code>mesflow-bootstrap</code> — route <code>/login</code> đọc lại <code>state.json</code> ở mỗi "
                 "lần đăng nhập, nên mật khẩu mới có hiệu lực ngay.",
        do_not="KHÔNG tự tay sửa <code>admin_password_hash</code> trong <code>state.json</code> bằng tay (hash sai "
               "định dạng sẽ khoá tài khoản hẳn). KHÔNG mở cổng 8098 ra Internet chỉ để 'dễ' truy cập khôi phục.",
        verify=[
            c(BROWSER, "http://127.0.0.1:18098/login", "Đăng nhập thử ngay bằng mật khẩu vừa đặt (qua tunnel Bước 05)."),
            c(SERVER, "sudo tail -5 /var/lib/mesflow-bootstrap/logs/audit.log",
              "Dòng mới nhất phải có <code>admin_password_reset</code>."),
        ],
    ),
    access_card(
        "Deploy Agent",
        if_forgotten="Còn giữ Recovery Code (in trong <code>FIRST_LOGIN.txt</code> lúc cài lần đầu, hoặc đã lưu "
                      "riêng) → dùng trang Forgot Password ngay trong Deploy Agent Web. Mất luôn Recovery Code → "
                      "dùng <code>/agent/local-reset</code>, chỉ hoạt động khi request tới TỪ chính localhost của "
                      "server (qua SSH tunnel) — không thể gọi từ Internet dù có biết URL.",
        access_required="SSH vào server để mở tunnel tới loopback (127.0.0.1:8090) — server không có desktop/"
                          "trình duyệt, trình duyệt luôn chạy trên laptop, tunnel là đường duy nhất để trình duyệt "
                          "đó 'trông giống' đang đứng trên chính server.",
        commands=[
            c(DEV, "ssh -N -L 18090:127.0.0.1:8090 mesflow-test", "Giữ terminal này mở."),
            c(BROWSER, "http://127.0.0.1:18090/agent/forgot-password",
                  "Nếu còn Recovery Code: nhập Recovery Code + mật khẩu mới."),
            c(BROWSER, "http://127.0.0.1:18090/agent/local-reset",
                  "Nếu KHÔNG còn Recovery Code: chỉ cần mật khẩu mới (route tự nhận diện request đến từ loopback "
                  "của chính server, không hỏi Recovery Code)."),
        ],
        expected="Thông báo 'Đã đặt lại mật khẩu. Hãy đăng nhập lại.' (Forgot Password) hoặc 'Đã đặt lại mật khẩu "
                 "từ máy chủ. Hãy đăng nhập.' (local-reset). File <code>FIRST_LOGIN.txt</code> (nếu còn) bị xoá.",
        do_not="KHÔNG bao giờ bind Deploy Agent ra <code>0.0.0.0:8090</code> để tránh phải mở tunnel — luôn giữ "
               "<code>127.0.0.1:8090</code> (xem mục Kiểm tra bảo mật). KHÔNG tự sửa "
               "<code>config/agent.json</code> bằng tay.",
        verify=[
            c(SERVER, "docker logs mesflow-deploy-agent --tail=50 | grep 'Administrator password reset'",
              "Xác nhận Agent đã thật sự ghi nhận việc đổi mật khẩu."),
            c(BROWSER, "http://127.0.0.1:18090/agent/", "Đăng nhập thử bằng mật khẩu mới."),
        ],
    ),
    access_card(
        "MESFlow",
        if_forgotten="Có <b>hai tình huống khác nhau</b> — đừng dùng nhầm cách của tình huống này cho tình huống kia:"
                      "<br><b>A. Quên mật khẩu một user THƯỜNG</b> (manager/supervisor/operator/viewer, hoặc admin "
                      "khác vẫn còn đăng nhập được) → dùng ngay màn hình <b>Người dùng hệ thống</b> trong MESFlow, "
                      "KHÔNG cần SSH."
                      "<br><b>B. Mất/quên đúng mật khẩu admin CUỐI CÙNG</b> (không còn ai đăng nhập được) → phải SSH "
                      "vào server và chạy CLI <code>reset-admin</code> — đây là lệnh DUY NHẤT hiện có trong image "
                      "MESFlow đang chạy cho tình huống này. (Mã nguồn workspace hiện có thêm một hàm "
                      "<code>reset_password()</code> an toàn hơn cho user thường, nhưng NÓ CHƯA nằm trong bất kỳ "
                      "bản MESFlow nào đã build/deploy — xác nhận trực tiếp trên container đang chạy: "
                      "<code>grep -o \"funcs={[^}]*}\" /app/mesflow/cli.py</code> bên trong container không liệt kê "
                      "<code>reset-password</code>. Đừng dùng lệnh đó cho tới khi nó thật sự có trong một bản đã "
                      "deploy.)",
        access_required="Tình huống A: chỉ cần một tài khoản còn đăng nhập được với quyền <code>users.manage</code> "
                          "(thường là admin) — không cần SSH. Tình huống B: SSH vào server + quyền chạy "
                          "<code>docker exec</code> trên host đó (không cần quyền PostgreSQL trực tiếp).",
        commands=[
            c(DEV, "ssh <server>", "Bước A — kết nối tới server đang chạy MESFlow từ laptop."),
            c(MESFLOW_SERVER, "docker ps --filter name=mesflow-app",
              "Bước B — xác nhận container mesflow-app đang chạy trước khi exec vào."),
            c(MESFLOW_SERVER, "docker exec mesflow-app python -c "
                       "'from mesflow.core.config import settings; print(settings.admin_username)'",
              "Bước C — xác nhận đúng username admin đang cấu hình, KHÔNG lộ mật khẩu."),
            c(MESFLOW_SERVER, 'read -s -p "Mật khẩu admin mới: " NEWPASS\necho',
              "Bước D — đọc mật khẩu mới vào biến shell, không hiện lên màn hình, không nằm trong lịch sử lệnh."),
            c(MESFLOW_SERVER, 'docker exec \\\n  -e MESFLOW_ADMIN_PASSWORD="$NEWPASS" \\\n  mesflow-app \\\n  '
                       'python -m mesflow.cli reset-admin',
              "Bước E — thực hiện reset thật. <code>-e MESFLOW_ADMIN_PASSWORD=\"$NEWPASS\"</code> chỉ set biến môi "
              "trường cho đúng tiến trình exec này, không ghi đè environment gốc của container."),
            c(MESFLOW_SERVER, "unset NEWPASS", "Bước F — xoá biến shell ngay sau khi dùng xong."),
        ],
        expected="<code>[SEED] Administrator password reset for &lt;username&gt;; id=&lt;id&gt;</code>. Không cần "
                 "restart PostgreSQL, không cần restart <code>mesflow-app</code> — lệnh chạy ngay bên trong tiến "
                 "trình container đang sống, ghi thẳng xuống DB qua UPDATE. Chỉ đúng một hàng "
                 "(<code>settings.admin_username</code>) bị đổi; role/quyền của các user khác không bị đụng tới. "
                 "<code>reset-admin</code> (theo đúng code hiện tại) LUÔN gán lại <code>role='admin'</code> và "
                 "<code>active=true</code> cho tài khoản đó mỗi lần chạy — đúng ý nghĩa 'khôi phục tài khoản admin', "
                 "không phải sự cố.",
        do_not="KHÔNG gõ mật khẩu thẳng vào dòng lệnh, ví dụ "
               "<code>docker exec -e MESFLOW_ADMIN_PASSWORD=MySecret123 ...</code> — giá trị đó nằm luôn trong lịch "
               "sử shell (<code>~/.bash_history</code>) và trong danh sách tiến trình lúc đang chạy. Luôn theo đúng "
               "thứ tự <code>read -s</code> → biến shell → <code>docker exec</code> → <code>unset</code> ở trên. "
               "KHÔNG bao giờ in mật khẩu ra màn hình/log. KHÔNG ghi mật khẩu khôi phục vào repo, README, hay "
               "<code>.env</code> — trừ khi bạn CHỦ ĐỘNG đang đổi luôn nguồn secret bền vững (xem cảnh báo "
               "<code>MESFLOW_ADMIN_PASSWORD</code> bên dưới). KHÔNG dùng <code>reset-admin</code> cho bảo trì tài "
               "khoản thông thường (đổi mật khẩu cho manager/supervisor/operator/viewer) — dùng màn hình Người dùng "
               "hệ thống cho việc đó, <code>reset-admin</code> chỉ dành riêng cho đúng một tài khoản admin cố định. "
               "KHÔNG bao giờ UPDATE trực tiếp cột <code>password_hash</code> bằng SQL tay.",
        verify=[
            c(BROWSER, "https://<mesflow-url>/login", "Đăng nhập thử ngay bằng mật khẩu mới."),
        ],
    ),
]

MESFLOW_ADMIN_PASSWORD_WARNING = (
    "Riêng MESFlow cũng có một điểm dễ gây nhầm tương tự Deploy Agent, nhưng khác cơ chế: đọc "
    "<code>mesflow/compose.yml</code> xác nhận service <code>mesflow-app</code> dùng "
    "<code>env_file: [.env]</code> — nghĩa là TOÀN BỘ nội dung <code>/opt/mesflow/.env</code>, bao gồm cả "
    "<code>MESFLOW_ADMIN_PASSWORD</code> nếu có, được nạp vào container mỗi lần khởi động. Đọc "
    "<code>scripts/docker-entrypoint.sh</code> xác nhận entrypoint gọi <code>seed-admin</code> ở MỖI lần khởi động "
    "container — nhưng <code>seed_admin()</code> tự kiểm tra <code>repo.count()==0</code> trước, nên nó chỉ tạo "
    "admin ở lần khởi động ĐẦU TIÊN (chưa có user nào); một lần restart/recreate container BÌNH THƯỜNG SAU NÀY "
    "KHÔNG tự động ghi đè lại mật khẩu admin đã reset — đã xác minh trực tiếp trong code, không suy đoán. Rủi ro "
    "thật nằm ở chỗ khác: nếu sau này có ai (hoặc một script khác) chạy lại <code>reset-admin</code> mà KHÔNG tự "
    "tay truyền <code>-e MESFLOW_ADMIN_PASSWORD=...</code>, lệnh đó sẽ âm thầm dùng đúng giá trị đang nằm trong "
    "<code>/opt/mesflow/.env</code> lúc đó (qua <code>env_file</code>) — có thể là một mật khẩu cũ/yếu bạn tưởng đã "
    "thay. Nguồn sự thật bền vững (canonical secret source) là <code>/opt/mesflow/.env</code>'s "
    "<code>MESFLOW_ADMIN_PASSWORD</code>/<code>MESFLOW_ADMIN_USERNAME</code> — nếu bạn muốn mật khẩu vừa reset "
    "cũng là giá trị mà lần <code>reset-admin</code> kế tiếp sẽ dùng, cập nhật luôn file đó (0600, chỉ root đọc "
    "được), đừng chỉ đổi qua <code>-e</code> một lần rồi quên."
)

RECOVERY_ACCESS_ENV_WARNING = (
    "Riêng Deploy Agent có một điểm dễ gây nhầm: nếu biến môi trường "
    "<code>MESFLOW_AGENT_ADMIN_PASSWORD</code> đang được set (trong "
    "<code>deploy-agent/docker/.env</code> hoặc shell env lúc chạy <code>docker compose up</code>), thì MỖI LẦN "
    "container được tạo lại (update, rollback, recreate) sẽ tự động ghi ĐÈ <code>password_hash</code> về đúng giá "
    "trị của biến đó — âm thầm huỷ tác dụng của một lần reset qua local-reset/forgot-password trước đó "
    "(<code>ensure_config()</code> trong <code>deploy-agent/agent.py</code> chạy lại mỗi lần tiến trình khởi động). "
    "Mặc định biến này để trống (không set) nên hành vi này không xảy ra trên một máy cài mặc định — nhưng nếu bạn "
    "CÓ set nó, hãy coi nó là nguồn sự thật (canonical secret source): sau khi reset xong, cập nhật lại (hoặc bỏ "
    "hẳn) <code>MESFLOW_AGENT_ADMIN_PASSWORD</code> để khớp, nếu không lần recreate kế tiếp sẽ đưa mật khẩu cũ "
    "quay lại."
)

RECOVERY_ACCESS_CLI_FALLBACK = (
    "<b>Dự phòng dòng lệnh cho Deploy Agent</b> — nếu vì lý do nào đó không dùng được cả hai route web ở trên: "
    "<code>deploy-agent/reset_password.py</code> (script Python độc lập, cần <code>werkzeug</code>) ghi thẳng vào "
    "<code>config/agent.json</code>. Lưu ý mặc định <code>--home</code> của script này trỏ tới đường dẫn Windows "
    "(<code>C:\\WorkshopManagementAgent</code>, cho biến thể cài trên Windows) — với server Linux/Docker đang mô tả "
    "trong hướng dẫn này, phải trỏ đúng thư mục dữ liệu thật bằng "
    "<code>--home /var/lib/mesflow-deploy-agent</code>. Cách an toàn nhất để chạy đúng phiên bản Python có sẵn "
    "<code>werkzeug</code> là qua chính venv của Agent nếu cài kiểu legacy (non-Docker); với bản Docker hiện tại, "
    "ưu tiên <code>/agent/local-reset</code> ở trên trước — nó không cần dừng container hay cài thêm gì."
)

EMERGENCY_ACCESS_MATRIX = [
    {"forgot": "Mật khẩu user MESFlow thường (không phải admin)", "need": "Một tài khoản MESFlow admin còn đăng nhập được",
     "recovery": "Người dùng hệ thống → chọn user → Reset mật khẩu"},
    {"forgot": "Mật khẩu admin MESFlow (mất/quên đúng tài khoản admin cuối cùng)", "need": "SSH vào server MESFlow",
     "recovery": "docker exec ... mesflow-app python -m mesflow.cli reset-admin"},
    {"forgot": "Mật khẩu Deploy Agent", "need": "SSH (tunnel tới loopback) hoặc còn Recovery Code",
     "recovery": "/agent/local-reset · /agent/forgot-password · reset_password.py (dự phòng)"},
    {"forgot": "Mật khẩu Bootstrap", "need": "SSH vào server", "recovery": "Script reset cục bộ (bin/reset-admin-password)"},
]
LOST_SSH_NOTE = (
    "Mất luôn SSH → không cơ chế reset nào ở trên giúp được (Bootstrap/Deploy Agent/MESFlow đều yêu cầu SSH trước "
    "tiên) → phải dùng console/recovery access của nhà cung cấp hạ tầng (cloud console, out-of-band KVM, ...), "
    "không phải vấn đề phần mềm MESFlow."
)

RECOVERY_SECURITY_WARNINGS = [
    "Không bao giờ mở public các cổng quản trị (8098 Bootstrap, 8090 Deploy Agent, cổng đăng nhập MESFlow) ra "
    "Internet chỉ để 'dễ' khôi phục — luôn đi qua SSH tunnel như hướng dẫn ở trên.",
    "Không bao giờ xoá file/DB xác thực (state.json, config/agent.json, bảng users) để 'reset cho nhanh'.",
    "Không bao giờ tự tay sửa password_hash trong bất kỳ file hay bảng nào — luôn dùng đúng script/CLI đã kiểm "
    "chứng ở trên, chúng tự lo đúng định dạng hash + audit log.",
    "Không bao giờ tắt xác thực toàn cục (bypass đăng nhập) để né việc quên mật khẩu.",
    "Không dùng chung một mật khẩu admin cho cả Bootstrap, Deploy Agent và MESFlow — lộ một nơi thì mất cả ba.",
]

# --------------------------------------------------------------------------
# 5. Recovery decision tree
# --------------------------------------------------------------------------
RECOVERY_TREE = [
    {"q": "SSH kết nối được vào server không?", "no": "Vấn đề hạ tầng/nhà cung cấp/mạng — kiểm tra qua console nhà "
                                                       "cung cấp, không phải lỗi phần mềm MESFlow.", "yes_next": True},
    {"q": "Bootstrap healthy? (curl 127.0.0.1:8098/health)",
     "no": "sudo systemctl restart mesflow-bootstrap  →  kiểm tra lại", "yes_next": True},
    {"q": "Deploy Agent healthy? (curl 127.0.0.1:8090/agent/health)",
     "no": "Bootstrap → Start/Restart/Reinstall Deploy Agent (Overview hoặc Install Deploy Agent)", "yes_next": True},
    {"q": "Docker khả dụng? (docker ps chạy được, docker info không lỗi)",
     "no": "Kiểm tra dịch vụ Docker: sudo systemctl status docker — không tự ý cài lại Docker khi chưa rõ nguyên nhân",
     "yes_next": True},
    {"q": "PostgreSQL healthy? (trong /agent/health: mes.docker.service_health.postgres)",
     "no": "Chẩn đoán bằng docker logs vào container postgres — TUYỆT ĐỐI KHÔNG tự ý tạo lại database", "yes_next": True},
    {"q": "MESFlow đang chạy? (mes.online: true)",
     "no": "Start lại hoặc redeploy đúng bản đã biết là tốt (known-good release) qua Deploy Agent — không build mới "
           "giữa chừng", "yes_next": True},
    {"q": "nginx/gateway healthy? (nếu compose của bạn có thành phần này)",
     "no": "Restart/kiểm tra cấu hình gateway — đây là thao tác cần phê duyệt người theo AGENTS.md (nginx cutover/"
           "reload ảnh hưởng production)", "yes_next": False},
]

# --------------------------------------------------------------------------
# 6. Status checklist
# --------------------------------------------------------------------------
CHECKLIST_GENERAL = [
    "SSH kết nối được (Bước 02)",
    "SERVER ROLE đã xác minh đúng ý định (Bước 06)",
    "Bootstrap healthy (curl :8098/health)",
    "Bootstrap chỉ bind localhost (ss -ltnp cho thấy 127.0.0.1:8098, không phải 0.0.0.0:8098)",
    "Docker healthy (docker ps chạy được, không lỗi)",
    "Deploy Agent healthy (curl :8090/agent/health → ok: true)",
    "Deploy Agent đúng vai trò (server_role khớp máy)",
    "PostgreSQL healthy (mes.docker.service_health.postgres = healthy)",
    "MESFlow đã deploy (mes.online: true)",
    "QA Center đã deploy (qa.online: true)",
    "MESFlow health PASS (mes.health_payload.status = healthy)",
    "QA health PASS (qa.payload.ok = true)",
    "Bằng chứng Test đã ghi nhận (LOCAL_PASS + TEST_PASS hiển thị trên Deploy Agent Web)",
]

CHECKLIST_PRODUCTION = [
    "Backup đã xác minh (Deploy Agent → Backup / DB / Storage — có bản backup gần nhất, verification_status ổn)",
    "TEST_PASS đã đạt cho đúng version định deploy",
    "server_role của máy đích = PRODUCTION (đã tự kiểm tra, không suy đoán)",
    "Artifact SHA/digest đã đối chiếu khớp giữa bản đã LOCAL_PASS/TEST_PASS và bản sắp deploy",
    "Có phê duyệt người tường minh cho lần deploy Production này (không dựa vào các lần trước)",
]

# --------------------------------------------------------------------------
# 7. Glossary
# --------------------------------------------------------------------------
GLOSSARY = [
    ("Artifact", "Gói kết quả build đã đóng băng (ZIP + metadata: version, SHA256, digest) — thứ duy nhất được phép "
                  "đi qua Test rồi Production, không bao giờ build lại giữa chừng."),
    ("Image", "Docker image — bản đóng gói ứng dụng thành lớp filesystem bất biến, chạy được bằng container."),
    ("Container", "Một tiến trình đang chạy từ một image, cô lập với host và các container khác."),
    ("Docker Compose", "Công cụ mô tả và khởi chạy nhiều container liên quan (service) bằng một hoặc nhiều file YAML."),
    ("Bootstrap", "Dịch vụ web độc lập, cổng 8098, dựng máy Ubuntu trống và cài/cứu hộ Deploy Agent."),
    ("Deploy Agent", "Control plane build/deploy/vận hành thật sự cho MESFlow và QA Center, cổng 8090."),
    ("Production Test", "Server test riêng, gần giống Production, dùng để thử artifact trước khi lên thật."),
    ("Production", "Máy chạy thật cho người dùng cuối, luôn cần phê duyệt người mỗi lần deploy."),
    ("Release", "Một version đã build xong, đóng băng metadata dưới artifacts/releases/<version>/."),
    ("Promote", "Đưa ĐÚNG artifact đã pass ở môi trường trước sang môi trường kế tiếp, không build lại."),
    ("Rollback", "Khôi phục lại phiên bản/image trước đó khi phiên bản mới không healthy."),
    ("Health check", "Kiểm tra tự động xem một dịch vụ có đang hoạt động đúng không, qua endpoint /health."),
    ("SHA256", "Hàm băm mật mã dùng để xác minh một file không bị thay đổi/hỏng khi truyền/lưu trữ."),
    ("Digest", "Định danh bất biến của một Docker image, tính từ nội dung — đáng tin hơn tag (tag có thể bị dời)."),
    ("Schema migration", "Thay đổi cấu trúc database (Alembic) — luôn cần kiểm tra migration_head khớp kỳ vọng."),
    ("SSH tunnel", "Đường hầm mã hoá qua SSH, cho phép mở một cổng nội bộ của server ra máy laptop mà không public "
                     "cổng đó ra Internet."),
]


def all_step_ids() -> list[str]:
    return [s["id"] for s in STEPS]


# --------------------------------------------------------------------------
# Markdown renderer — keeps docs/MESFLOW_SERVER_DEPLOYMENT_GUIDE.md in sync
# with this same data. Run bootstrap/scripts/generate_guide_doc.py after
# editing anything above.
# --------------------------------------------------------------------------
def _md_text(s: str | None) -> str:
    """Convert an author-controlled HTML-ish snippet (<code>, <b>, <br>, and
    &lt;PLACEHOLDER&gt; entities used so it also renders correctly on the
    HTML page -- see the safe-render notes on guide_deployment.html) into
    plain Markdown. Markdown needs neither HTML tags nor entities."""
    if not s:
        return ""
    s = s.replace("<code>", "`").replace("</code>", "`")
    s = s.replace("<b>", "**").replace("</b>", "**")
    s = s.replace("<br>", "\n\n")
    return _html.unescape(s)


def _md_cmd(cmd_: dict) -> str:
    lines = [f"**{cmd_['machine_label']}**", "```bash", cmd_["code"], "```"]
    if cmd_.get("note"):
        lines.append(f"> {_md_text(cmd_['note'])}")
    return "\n".join(lines)


def render_markdown() -> str:
    out = []
    out.append("# Hướng dẫn triển khai MESFlow — từ máy trống tới server chạy thật\n")
    out.append(f"_Phiên bản tài liệu: {GUIDE_VERSION} — sinh tự động từ `bootstrap/guide_content.py`, "
                "không sửa tay file này. Cùng nội dung với trang web `/guide/deployment` trong Bootstrap._\n")

    out.append("## Kiến trúc triển khai\n")
    out.append("```\n" + ARCHITECTURE_DIAGRAM + "\n```\n")
    for item in ARCHITECTURE_EXPLAIN:
        out.append(f"**{item['term']}**\n: {_md_text(item['text'])}\n")

    out.append("\n## Vai trò server (SERVER_ROLE) — luôn xác minh, không đoán\n")
    out.append(_md_text(SERVER_ROLE["intro"]) + "\n")
    out.append("Giá trị hợp lệ: " + ", ".join(f"`{v}`" for v in SERVER_ROLE["canonical_values"]) + "\n")
    out.append("| Máy | Compose override | Đặt gì |\n|---|---|---|")
    for row in SERVER_ROLE["compose_table"]:
        out.append(f"| {row['host']} | `{row['file']}` | {_md_text(row['sets'])} |")
    out.append("")
    out.append(_md_text(SERVER_ROLE["how_set"]) + "\n")
    out.append(_md_text(SERVER_ROLE["install_default"]) + "\n")
    out.append("**Cách kiểm tra:**\n")
    for cmd_ in SERVER_ROLE["verify_commands"]:
        out.append(_md_cmd(cmd_) + "\n")
    out.append("**⚠ " + _md_text(SERVER_ROLE["warning"]) + "**\n")
    out.append("\n**Nếu vai trò sai — cách sửa:**\n")
    for cmd_ in SERVER_ROLE["fix_commands"]:
        out.append(_md_cmd(cmd_) + "\n")

    out.append("\n## Hành trình triển khai — 12 bước\n")
    for s in STEPS:
        out.append(f"### {s['num']}. {s['title']}\n")
        out.append(f"**MỤC ĐÍCH:** {_md_text(s['purpose'])}\n")
        out.append(f"**THỰC HIỆN Ở ĐÂU:** {_md_text(s['where'])}\n")
        for b in s["blocks"]:
            if b["heading"]:
                out.append(f"**{b['heading']}**\n")
            if b.get("text"):
                out.append(_md_text(b["text"]) + "\n")
            for cmd_ in b["commands"]:
                out.append(_md_cmd(cmd_) + "\n")
            if b.get("note"):
                out.append(f"> {_md_text(b['note'])}\n")
        out.append(f"**KẾT QUẢ MONG ĐỢI:** {_md_text(s['expected'])}\n")
        out.append(f"**NẾU LỖI THÌ LÀM GÌ:** {_md_text(s['on_error'])}\n")
        out.append(f"**TIẾP THEO:** {s['next']}\n")

    out.append("\n## Sự cố thường gặp\n")
    for f in FAILURES:
        out.append(f"### {f['title']}\n")
        out.append(f"**Triệu chứng:**\n```\n{f['symptom']}\n```\n")
        if f["diagnose"]:
            out.append("**Chẩn đoán:**\n")
            for cmd_ in f["diagnose"]:
                out.append(_md_cmd(cmd_) + "\n")
        out.append(f"**Xử lý:** {_md_text(f['fix'])}\n")
        for cmd_ in f.get("extra_commands", []):
            out.append(_md_cmd(cmd_) + "\n")

    out.append("\n## Quên mật khẩu / Mất quyền truy cập\n")
    for a in RECOVERY_ACCESS:
        out.append(f"### {a['system']}\n")
        out.append(f"**Nếu quên:** {_md_text(a['if_forgotten'])}\n")
        out.append(f"**Cần quyền gì:** {_md_text(a['access_required'])}\n")
        out.append("**Lệnh / URL chính xác:**\n")
        for cmd_ in a["commands"]:
            out.append(_md_cmd(cmd_) + "\n")
        out.append(f"**Kết quả mong đợi:** {_md_text(a['expected'])}\n")
        out.append(f"**Không được làm:** {_md_text(a['do_not'])}\n")
        out.append("**Cách xác nhận đã khôi phục:**\n")
        for cmd_ in a["verify"]:
            out.append(_md_cmd(cmd_) + "\n")
    out.append(_md_text(RECOVERY_ACCESS_ENV_WARNING) + "\n")
    out.append(_md_text(RECOVERY_ACCESS_CLI_FALLBACK) + "\n")
    out.append(_md_text(MESFLOW_ADMIN_PASSWORD_WARNING) + "\n")
    out.append("\n**Ma trận truy cập khẩn cấp**\n")
    out.append("| Quên gì | Cần gì | Cách khôi phục |\n|---|---|---|")
    for row in EMERGENCY_ACCESS_MATRIX:
        out.append(f"| {row['forgot']} | {row['need']} | {_md_text(row['recovery'])} |")
    out.append("")
    out.append(f"\n⚠ {LOST_SSH_NOTE}\n")
    out.append("\n**Cảnh báo bảo mật**\n")
    for warn in RECOVERY_SECURITY_WARNINGS:
        out.append(f"- ⚠ {_md_text(warn)}")

    out.append("\n## Cây quyết định phục hồi\n")
    out.append("Đi từ trên xuống, dừng lại ở câu đầu tiên trả lời KHÔNG:\n")
    for node in RECOVERY_TREE:
        out.append(f"- **{node['q']}**\n  - Không → {node['no']}\n  - Có → đi tiếp câu hỏi kế tiếp")

    out.append("\n## Checklist trạng thái\n")
    out.append("### Chung\n")
    for item in CHECKLIST_GENERAL:
        out.append(f"- [ ] {item}")
    out.append("\n### Riêng cho Production\n")
    for item in CHECKLIST_PRODUCTION:
        out.append(f"- [ ] {item}")

    out.append("\n## Thuật ngữ\n")
    for term, definition in GLOSSARY:
        out.append(f"**{term}**\n: {definition}\n")

    return "\n".join(out) + "\n"
